name:
description: convert from GTF to BED format
  - convert2bed
tools:
  - convert2bed:
      description: convert from GTF to BED format
      homepage: https://github.com/bedops/bedops
      documentation: https://bedops.readthedocs.io/en/latest/index.html
      tool_dev_url: https://github.com/bedops/bedops
      doi: ""
      licence: ["GNU GENERAL PUBLIC LICENSE"]

input:
  - gtf:
      type: file
      description: Path to GTF file
      pattern: "*.{gtf*}"

output:
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - bed:
      type: file
      description: bed file
      pattern: "*.bed"

authors:
  - "@rannick"
